"""
StorageBackend Protocol — the contract that every storage backend must satisfy.

SQLite, Postgres, DynamoDB (and future backends) all implement this interface.
The rest of the system (core, graph, consolidation, decay, API, CLI) calls only
these methods and never touches backend-specific code.
"""

from typing import List, Optional, Dict, Set, Tuple, Protocol, runtime_checkable

import numpy as np

from .models import (
    Memory, MemoryType, MemoryLink, WorkingMemoryItem,
    KnowledgePage, ProvenanceEntry, MemoryVersion,
)


@runtime_checkable
class StorageBackend(Protocol):
    """
    Unified storage interface for the Memory Layer.

    Implementations:
        - MemoryStorage         (SQLite, local-first, default)
        - PostgresStorage       (Postgres, self-hosted or cloud)
        - DynamoStorage         (AWS DynamoDB, serverless)
    """

    # ── Metadata ──

    def get_meta(self, key: str) -> Optional[str]: ...
    def set_meta(self, key: str, value: str) -> None: ...
    def has_memories(self) -> bool: ...
    def count_active_memories_with_embeddings(self) -> int: ...
    def get_sample_embedding_dimension(self) -> Optional[int]: ...
    def clear_all_embeddings(self) -> None: ...

    # ── Memory CRUD ──

    def store_memory(self, memory: Memory) -> str: ...
    def get_memory(self, memory_id: str) -> Optional[Memory]: ...
    def get_memories_by_ids(self, memory_ids: List[str]) -> List[Memory]: ...
    def get_all_memories(
        self,
        memory_type: Optional[MemoryType] = None,
        active_only: bool = True,
        namespace: Optional[str] = None,
        tags: Optional[List[str]] = None,
    ) -> List[Memory]: ...
    def update_memory(self, memory: Memory) -> None: ...
    def deactivate_memory(self, memory_id: str) -> None: ...
    def forget_memory(self, memory_id: str, hard: bool = False) -> None: ...
    def bulk_forget(
        self,
        *,
        namespace: Optional[str] = None,
        tags: Optional[List[str]] = None,
        memory_type: Optional[MemoryType] = None,
        older_than_hours: Optional[float] = None,
        hard: bool = False,
    ) -> int: ...

    # ── Embeddings / Passages ──

    def get_memories_with_embeddings(
        self,
        memory_type: Optional[MemoryType] = None,
        min_strength: float = 0.0,
        namespace: Optional[str] = None,
    ) -> List[Tuple[Memory, np.ndarray]]: ...
    def store_passages(self, memory_id: str, passages: List[Dict]) -> None: ...
    def get_all_passage_embeddings(
        self, min_strength: float = 0.0,
    ) -> List[Tuple[str, np.ndarray]]: ...
    def delete_passages_for_memory(self, memory_id: str) -> None: ...

    # ── Links ──

    def store_link(self, link: MemoryLink) -> str: ...
    def get_links_for(self, memory_id: str) -> List[MemoryLink]: ...
    def get_links_for_ids(self, memory_ids: List[str]) -> List[MemoryLink]: ...
    def get_all_links(self) -> List[MemoryLink]: ...

    # ── Working Memory ──

    def store_working_item(self, item: WorkingMemoryItem) -> None: ...
    def get_working_memory(self, limit: int = 20) -> List[WorkingMemoryItem]: ...
    def clear_working_memory(self) -> None: ...
    def trim_working_memory(self, keep_last: int = 20) -> None: ...

    # ── Consolidation ──

    def log_consolidation(
        self,
        consolidation_id: str,
        source_ids: List[str],
        result_id: str,
        strategy: str = "pattern_extraction",
    ) -> None: ...
    def get_consolidated_episode_ids(self) -> Set[str]: ...
    def get_consolidation_count(self) -> int: ...

    # ── Statistics ──

    def get_counts(self, namespace: Optional[str] = None) -> Dict[str, int]: ...
    def get_avg_strength(self) -> float: ...
    def get_avg_importance(self) -> float: ...
    def get_oldest_memory_age_hours(self) -> float: ...
    def get_most_accessed_memory_id(self) -> Optional[str]: ...

    # ── Knowledge Pages ──

    def store_knowledge_page(self, page: KnowledgePage) -> str: ...
    def get_knowledge_page(self, page_id: str) -> Optional[KnowledgePage]: ...
    def get_knowledge_page_by_entity(self, entity_id: str) -> Optional[KnowledgePage]: ...
    def get_knowledge_page_by_title(self, title: str) -> Optional[KnowledgePage]: ...
    def get_all_knowledge_pages(self, page_type: Optional[str] = None) -> List[KnowledgePage]: ...
    def update_knowledge_page(self, page: KnowledgePage) -> None: ...
    def delete_knowledge_page(self, page_id: str) -> None: ...
    def link_memory_to_page(self, page_id: str, memory_id: str) -> None: ...
    def get_memories_for_page(self, page_id: str) -> List[str]: ...
    def get_pages_for_memory(self, memory_id: str) -> List[KnowledgePage]: ...

    # ── Provenance ──

    def store_provenance(self, entry: ProvenanceEntry) -> str: ...
    def get_provenance(self, memory_id: str) -> List[ProvenanceEntry]: ...
    def get_provenance_chain(self, memory_id: str) -> List[ProvenanceEntry]: ...

    # ── Memory Versions ──

    def store_memory_version(self, version: MemoryVersion) -> str: ...
    def get_version_history(self, memory_id: str) -> List[MemoryVersion]: ...

    # ── Lint Helpers ──

    def get_stale_memories(self, max_age_days: int = 14) -> List[Memory]: ...
    def get_orphan_memories(self) -> List[Memory]: ...
